name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH agent and keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Remote SSH Deployment Commands
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@213.35.118.26 "
            cd /var/www/piyoh-pos &&
            git pull &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan optimize
          "
